# Generated by Django 3.1.2 on 2020-12-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('show_date', 'artist', 'venue')},
        ),
    ]
