# Generated by Django 3.1.2 on 2020-12-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_merge_20201211_0203'),
        ('lmn', '0006_note_rating'),
    ]

    operations = [
    ]
